<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9f043a8c-fbf2-444d-8459-734582dff9ee</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.0" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="HeartCheckML.zip" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
